<?php $this->widget('bootstrap.widgets.TbExtendedGridView', array(
    'type'=>'striped bordered condensed',
    'id'=>'taxones-grid',
    'dataProvider'=>$listTaxones,
    'ajaxUrl'=>array('taxon/busqueda'),
	'columns'=>array(
    	array( 'name'=>'id', 'header'=> Yii::t('app', 'Id')),
    	//array( 'name'=>'name', 'header'=> Yii::t('app', 'Nombre Ingresado')),
    	array( 'name'=>'kingdom', 'header'=> Yii::t('app', 'Reino')),
		array( 'name'=>'phylum', 'header'=> Yii::t('app', 'Filo')),
    	array( 'name'=>'class', 'header'=> Yii::t('app', 'Clase')),
    	array( 'name'=>'order', 'header'=> Yii::t('app', 'Orden')),
		array( 'name'=>'family', 'header'=> Yii::t('app', 'Familia')),
		array( 'name'=>'genus', 'header'=> Yii::t('app', 'Género')),
    	array( 'name'=>'epitetoes', 'header'=> Yii::t('app', 'Epíteto Específico')),
    	array( 'name'=>'epitetoin', 'header'=> Yii::t('app', 'Epíteto Infraespecífico')),
    	array( 'name'=>'rank', 'header'=> Yii::t('app', 'Categoría')),
    	array( 'name'=>'author', 'header'=> Yii::t('app', 'Autor')),
    	array( 'name'=>'scientificName', 'header'=> Yii::t('app', 'Nombre Científico')),
    	array( 'name'=>'identifier', 'header'=> Yii::t('app', 'LSID')),
	),
)); ?>